// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "cs_auth_challenge.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


void LuabindPB_CSAuthChallenge_Register(lua_State* L) {
  luabind::module(L) [
    luabind::class_< ::hammer::message::CSAuthChallenge, ::google::protobuf::Message, ::google::protobuf::MessageLite>("CSAuthChallenge")
      .def(luabind::constructor<>())
      .property("uname", (const std::string& (::hammer::message::CSAuthChallenge::*)(void) const)&::hammer::message::CSAuthChallenge::uname, (void (::hammer::message::CSAuthChallenge::*)(const char*))&::hammer::message::CSAuthChallenge::set_uname)
  ];
}

//////////////////////////////////////////////////
void LuabindPB_cs_auth_challenge_RegisterAll(lua_State* L) {
  LuabindPB_CSAuthChallenge_Register(L);
}

//////////////////////////////////////////////////
