// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "cs_auth_proof.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


void LuabindPB_CSAuthProof_Register(lua_State* L) {
  luabind::module(L) [
    luabind::class_< ::hammer::message::CSAuthProof, ::google::protobuf::Message, ::google::protobuf::MessageLite>("CSAuthProof")
      .def(luabind::constructor<>())
      .property("uname", (const std::string& (::hammer::message::CSAuthProof::*)(void) const)&::hammer::message::CSAuthProof::uname, (void (::hammer::message::CSAuthProof::*)(const char*))&::hammer::message::CSAuthProof::set_uname)
      .property("hash_key", (const std::string& (::hammer::message::CSAuthProof::*)(void) const)&::hammer::message::CSAuthProof::hash_key, (void (::hammer::message::CSAuthProof::*)(const char*))&::hammer::message::CSAuthProof::set_hash_key)
  ];
}

//////////////////////////////////////////////////
void LuabindPB_cs_auth_proof_RegisterAll(lua_State* L) {
  LuabindPB_CSAuthProof_Register(L);
}

//////////////////////////////////////////////////
