// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "sc_auth_proof.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


void LuabindPB_SCAuthProof_Register(lua_State* L) {
  luabind::module(L) [
    luabind::class_< ::hammer::message::SCAuthProof, ::google::protobuf::Message, ::google::protobuf::MessageLite>("SCAuthProof")
      .def(luabind::constructor<>())
      .property("ret_code", (::google::protobuf::int32 (::hammer::message::SCAuthProof::*)(void) const)&::hammer::message::SCAuthProof::ret_code, (void (::hammer::message::SCAuthProof::*)(::google::protobuf::int32))&::hammer::message::SCAuthProof::set_ret_code)
      .property("player_id", (::google::protobuf::uint32 (::hammer::message::SCAuthProof::*)(void) const)&::hammer::message::SCAuthProof::player_id, (void (::hammer::message::SCAuthProof::*)(::google::protobuf::uint32))&::hammer::message::SCAuthProof::set_player_id)
  ];
}

//////////////////////////////////////////////////
void LuabindPB_sc_auth_proof_RegisterAll(lua_State* L) {
  LuabindPB_SCAuthProof_Register(L);
}

//////////////////////////////////////////////////
