// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "sc_auth_challenge.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


void LuabindPB_SCAuthChallenge_Register(lua_State* L) {
  luabind::module(L) [
    luabind::class_< ::hammer::message::SCAuthChallenge, ::google::protobuf::Message, ::google::protobuf::MessageLite>("SCAuthChallenge")
      .def(luabind::constructor<>())
      .property("ret_code", (::google::protobuf::int32 (::hammer::message::SCAuthChallenge::*)(void) const)&::hammer::message::SCAuthChallenge::ret_code, (void (::hammer::message::SCAuthChallenge::*)(::google::protobuf::int32))&::hammer::message::SCAuthChallenge::set_ret_code)
      .property("hash_key", (const std::string& (::hammer::message::SCAuthChallenge::*)(void) const)&::hammer::message::SCAuthChallenge::hash_key, (void (::hammer::message::SCAuthChallenge::*)(const char*))&::hammer::message::SCAuthChallenge::set_hash_key)
  ];
}

//////////////////////////////////////////////////
void LuabindPB_sc_auth_challenge_RegisterAll(lua_State* L) {
  LuabindPB_SCAuthChallenge_Register(L);
}

//////////////////////////////////////////////////
