// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "sc_server_challeng_ack.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


void LuabindPB_SCServerChallengeAck_Register(lua_State* L) {
  luabind::module(L) [
    luabind::class_< ::hammer::message::SCServerChallengeAck, ::google::protobuf::Message, ::google::protobuf::MessageLite>("SCServerChallengeAck")
      .def(luabind::constructor<>())
      .property("ret_code", (::google::protobuf::int32 (::hammer::message::SCServerChallengeAck::*)(void) const)&::hammer::message::SCServerChallengeAck::ret_code, (void (::hammer::message::SCServerChallengeAck::*)(::google::protobuf::int32))&::hammer::message::SCServerChallengeAck::set_ret_code)
  ];
}

//////////////////////////////////////////////////
void LuabindPB_sc_server_challeng_ack_RegisterAll(lua_State* L) {
  LuabindPB_SCServerChallengeAck_Register(L);
}

//////////////////////////////////////////////////
