// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_auth_proof.proto

#ifndef PROTOBUF_cs_5fauth_5fproof_2eproto__INCLUDED
#define PROTOBUF_cs_5fauth_5fproof_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cs_5fauth_5fproof_2eproto();
void protobuf_AssignDesc_cs_5fauth_5fproof_2eproto();
void protobuf_ShutdownFile_cs_5fauth_5fproof_2eproto();

class CSAuthProof;

// ===================================================================

class CSAuthProof : public ::google::protobuf::Message {
 public:
  CSAuthProof();
  virtual ~CSAuthProof();
  
  CSAuthProof(const CSAuthProof& from);
  
  inline CSAuthProof& operator=(const CSAuthProof& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSAuthProof& default_instance();
  
  void Swap(CSAuthProof* other);
  
  // implements Message ----------------------------------------------
  
  CSAuthProof* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string uname = 1;
  inline bool has_uname() const;
  inline void clear_uname();
  static const int kUnameFieldNumber = 1;
  inline const ::std::string& uname() const;
  inline void set_uname(const ::std::string& value);
  inline void set_uname(const char* value);
  inline void set_uname(const char* value, size_t size);
  inline ::std::string* mutable_uname();
  
  // required string hash_key = 2;
  inline bool has_hash_key() const;
  inline void clear_hash_key();
  static const int kHashKeyFieldNumber = 2;
  inline const ::std::string& hash_key() const;
  inline void set_hash_key(const ::std::string& value);
  inline void set_hash_key(const char* value);
  inline void set_hash_key(const char* value, size_t size);
  inline ::std::string* mutable_hash_key();
  
  // @@protoc_insertion_point(class_scope:hammer.message.CSAuthProof)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* uname_;
  static const ::std::string _default_uname_;
  ::std::string* hash_key_;
  static const ::std::string _default_hash_key_;
  friend void  protobuf_AddDesc_cs_5fauth_5fproof_2eproto();
  friend void protobuf_AssignDesc_cs_5fauth_5fproof_2eproto();
  friend void protobuf_ShutdownFile_cs_5fauth_5fproof_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CSAuthProof* default_instance_;
};
// ===================================================================


// ===================================================================

// CSAuthProof

// required string uname = 1;
inline bool CSAuthProof::has_uname() const {
  return _has_bit(0);
}
inline void CSAuthProof::clear_uname() {
  if (uname_ != &_default_uname_) {
    uname_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& CSAuthProof::uname() const {
  return *uname_;
}
inline void CSAuthProof::set_uname(const ::std::string& value) {
  _set_bit(0);
  if (uname_ == &_default_uname_) {
    uname_ = new ::std::string;
  }
  uname_->assign(value);
}
inline void CSAuthProof::set_uname(const char* value) {
  _set_bit(0);
  if (uname_ == &_default_uname_) {
    uname_ = new ::std::string;
  }
  uname_->assign(value);
}
inline void CSAuthProof::set_uname(const char* value, size_t size) {
  _set_bit(0);
  if (uname_ == &_default_uname_) {
    uname_ = new ::std::string;
  }
  uname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSAuthProof::mutable_uname() {
  _set_bit(0);
  if (uname_ == &_default_uname_) {
    uname_ = new ::std::string;
  }
  return uname_;
}

// required string hash_key = 2;
inline bool CSAuthProof::has_hash_key() const {
  return _has_bit(1);
}
inline void CSAuthProof::clear_hash_key() {
  if (hash_key_ != &_default_hash_key_) {
    hash_key_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& CSAuthProof::hash_key() const {
  return *hash_key_;
}
inline void CSAuthProof::set_hash_key(const ::std::string& value) {
  _set_bit(1);
  if (hash_key_ == &_default_hash_key_) {
    hash_key_ = new ::std::string;
  }
  hash_key_->assign(value);
}
inline void CSAuthProof::set_hash_key(const char* value) {
  _set_bit(1);
  if (hash_key_ == &_default_hash_key_) {
    hash_key_ = new ::std::string;
  }
  hash_key_->assign(value);
}
inline void CSAuthProof::set_hash_key(const char* value, size_t size) {
  _set_bit(1);
  if (hash_key_ == &_default_hash_key_) {
    hash_key_ = new ::std::string;
  }
  hash_key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSAuthProof::mutable_hash_key() {
  _set_bit(1);
  if (hash_key_ == &_default_hash_key_) {
    hash_key_ = new ::std::string;
  }
  return hash_key_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cs_5fauth_5fproof_2eproto__INCLUDED
