// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cs_auth_challenge.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

namespace {

const ::google::protobuf::Descriptor* CSAuthChallenge_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSAuthChallenge_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cs_5fauth_5fchallenge_2eproto() {
  protobuf_AddDesc_cs_5fauth_5fchallenge_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cs_auth_challenge.proto");
  GOOGLE_CHECK(file != NULL);
  CSAuthChallenge_descriptor_ = file->message_type(0);
  static const int CSAuthChallenge_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthChallenge, uname_),
  };
  CSAuthChallenge_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CSAuthChallenge_descriptor_,
      CSAuthChallenge::default_instance_,
      CSAuthChallenge_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthChallenge, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthChallenge, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CSAuthChallenge));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cs_5fauth_5fchallenge_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CSAuthChallenge_descriptor_, &CSAuthChallenge::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cs_5fauth_5fchallenge_2eproto() {
  delete CSAuthChallenge::default_instance_;
  delete CSAuthChallenge_reflection_;
}

void protobuf_AddDesc_cs_5fauth_5fchallenge_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027cs_auth_challenge.proto\022\016hammer.messag"
    "e\" \n\017CSAuthChallenge\022\r\n\005uname\030\001 \002(\tB\022\n\016h"
    "ammer.messageH\002", 95);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_auth_challenge.proto", &protobuf_RegisterTypes);
  CSAuthChallenge::default_instance_ = new CSAuthChallenge();
  CSAuthChallenge::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cs_5fauth_5fchallenge_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cs_5fauth_5fchallenge_2eproto {
  StaticDescriptorInitializer_cs_5fauth_5fchallenge_2eproto() {
    protobuf_AddDesc_cs_5fauth_5fchallenge_2eproto();
  }
} static_descriptor_initializer_cs_5fauth_5fchallenge_2eproto_;


// ===================================================================

const ::std::string CSAuthChallenge::_default_uname_;
#ifndef _MSC_VER
const int CSAuthChallenge::kUnameFieldNumber;
#endif  // !_MSC_VER

CSAuthChallenge::CSAuthChallenge()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CSAuthChallenge::InitAsDefaultInstance() {
}

CSAuthChallenge::CSAuthChallenge(const CSAuthChallenge& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CSAuthChallenge::SharedCtor() {
  _cached_size_ = 0;
  uname_ = const_cast< ::std::string*>(&_default_uname_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CSAuthChallenge::~CSAuthChallenge() {
  SharedDtor();
}

void CSAuthChallenge::SharedDtor() {
  if (uname_ != &_default_uname_) {
    delete uname_;
  }
  if (this != default_instance_) {
  }
}

void CSAuthChallenge::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSAuthChallenge::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSAuthChallenge_descriptor_;
}

const CSAuthChallenge& CSAuthChallenge::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cs_5fauth_5fchallenge_2eproto();  return *default_instance_;
}

CSAuthChallenge* CSAuthChallenge::default_instance_ = NULL;

CSAuthChallenge* CSAuthChallenge::New() const {
  return new CSAuthChallenge;
}

void CSAuthChallenge::Swap(CSAuthChallenge* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata CSAuthChallenge::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSAuthChallenge_descriptor_;
  metadata.reflection = CSAuthChallenge_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

// @@protoc_insertion_point(global_scope)
