// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cs_auth_proof.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

namespace {

const ::google::protobuf::Descriptor* CSAuthProof_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSAuthProof_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cs_5fauth_5fproof_2eproto() {
  protobuf_AddDesc_cs_5fauth_5fproof_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cs_auth_proof.proto");
  GOOGLE_CHECK(file != NULL);
  CSAuthProof_descriptor_ = file->message_type(0);
  static const int CSAuthProof_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthProof, uname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthProof, hash_key_),
  };
  CSAuthProof_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CSAuthProof_descriptor_,
      CSAuthProof::default_instance_,
      CSAuthProof_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthProof, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSAuthProof, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CSAuthProof));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cs_5fauth_5fproof_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CSAuthProof_descriptor_, &CSAuthProof::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cs_5fauth_5fproof_2eproto() {
  delete CSAuthProof::default_instance_;
  delete CSAuthProof_reflection_;
}

void protobuf_AddDesc_cs_5fauth_5fproof_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023cs_auth_proof.proto\022\016hammer.message\".\n"
    "\013CSAuthProof\022\r\n\005uname\030\001 \002(\t\022\020\n\010hash_key\030"
    "\002 \002(\tB\022\n\016hammer.messageH\002", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_auth_proof.proto", &protobuf_RegisterTypes);
  CSAuthProof::default_instance_ = new CSAuthProof();
  CSAuthProof::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cs_5fauth_5fproof_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cs_5fauth_5fproof_2eproto {
  StaticDescriptorInitializer_cs_5fauth_5fproof_2eproto() {
    protobuf_AddDesc_cs_5fauth_5fproof_2eproto();
  }
} static_descriptor_initializer_cs_5fauth_5fproof_2eproto_;


// ===================================================================

const ::std::string CSAuthProof::_default_uname_;
const ::std::string CSAuthProof::_default_hash_key_;
#ifndef _MSC_VER
const int CSAuthProof::kUnameFieldNumber;
const int CSAuthProof::kHashKeyFieldNumber;
#endif  // !_MSC_VER

CSAuthProof::CSAuthProof()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CSAuthProof::InitAsDefaultInstance() {
}

CSAuthProof::CSAuthProof(const CSAuthProof& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CSAuthProof::SharedCtor() {
  _cached_size_ = 0;
  uname_ = const_cast< ::std::string*>(&_default_uname_);
  hash_key_ = const_cast< ::std::string*>(&_default_hash_key_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CSAuthProof::~CSAuthProof() {
  SharedDtor();
}

void CSAuthProof::SharedDtor() {
  if (uname_ != &_default_uname_) {
    delete uname_;
  }
  if (hash_key_ != &_default_hash_key_) {
    delete hash_key_;
  }
  if (this != default_instance_) {
  }
}

void CSAuthProof::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSAuthProof::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSAuthProof_descriptor_;
}

const CSAuthProof& CSAuthProof::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cs_5fauth_5fproof_2eproto();  return *default_instance_;
}

CSAuthProof* CSAuthProof::default_instance_ = NULL;

CSAuthProof* CSAuthProof::New() const {
  return new CSAuthProof;
}

void CSAuthProof::Swap(CSAuthProof* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata CSAuthProof::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSAuthProof_descriptor_;
  metadata.reflection = CSAuthProof_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

// @@protoc_insertion_point(global_scope)
