// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cs_logout_req.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

namespace {

const ::google::protobuf::Descriptor* CSLogoutReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSLogoutReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cs_5flogout_5freq_2eproto() {
  protobuf_AddDesc_cs_5flogout_5freq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cs_logout_req.proto");
  GOOGLE_CHECK(file != NULL);
  CSLogoutReq_descriptor_ = file->message_type(0);
  static const int CSLogoutReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSLogoutReq, player_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSLogoutReq, type_),
  };
  CSLogoutReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CSLogoutReq_descriptor_,
      CSLogoutReq::default_instance_,
      CSLogoutReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSLogoutReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSLogoutReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CSLogoutReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cs_5flogout_5freq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CSLogoutReq_descriptor_, &CSLogoutReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cs_5flogout_5freq_2eproto() {
  delete CSLogoutReq::default_instance_;
  delete CSLogoutReq_reflection_;
}

void protobuf_AddDesc_cs_5flogout_5freq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023cs_logout_req.proto\022\016hammer.message\".\n"
    "\013CSLogoutReq\022\021\n\tplayer_id\030\001 \002(\r\022\014\n\004type\030"
    "\002 \002(\rB\022\n\016hammer.messageH\002", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_logout_req.proto", &protobuf_RegisterTypes);
  CSLogoutReq::default_instance_ = new CSLogoutReq();
  CSLogoutReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cs_5flogout_5freq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cs_5flogout_5freq_2eproto {
  StaticDescriptorInitializer_cs_5flogout_5freq_2eproto() {
    protobuf_AddDesc_cs_5flogout_5freq_2eproto();
  }
} static_descriptor_initializer_cs_5flogout_5freq_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int CSLogoutReq::kPlayerIdFieldNumber;
const int CSLogoutReq::kTypeFieldNumber;
#endif  // !_MSC_VER

CSLogoutReq::CSLogoutReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CSLogoutReq::InitAsDefaultInstance() {
}

CSLogoutReq::CSLogoutReq(const CSLogoutReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CSLogoutReq::SharedCtor() {
  _cached_size_ = 0;
  player_id_ = 0u;
  type_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CSLogoutReq::~CSLogoutReq() {
  SharedDtor();
}

void CSLogoutReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSLogoutReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSLogoutReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSLogoutReq_descriptor_;
}

const CSLogoutReq& CSLogoutReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cs_5flogout_5freq_2eproto();  return *default_instance_;
}

CSLogoutReq* CSLogoutReq::default_instance_ = NULL;

CSLogoutReq* CSLogoutReq::New() const {
  return new CSLogoutReq;
}

void CSLogoutReq::Swap(CSLogoutReq* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata CSLogoutReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSLogoutReq_descriptor_;
  metadata.reflection = CSLogoutReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

// @@protoc_insertion_point(global_scope)
