// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message_null.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

namespace {

const ::google::protobuf::Descriptor* MessageNull_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageNull_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_message_5fnull_2eproto() {
  protobuf_AddDesc_message_5fnull_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "message_null.proto");
  GOOGLE_CHECK(file != NULL);
  MessageNull_descriptor_ = file->message_type(0);
  static const int MessageNull_offsets_[1] = {
  };
  MessageNull_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageNull_descriptor_,
      MessageNull::default_instance_,
      MessageNull_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageNull, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageNull, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageNull));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_message_5fnull_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageNull_descriptor_, &MessageNull::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_message_5fnull_2eproto() {
  delete MessageNull::default_instance_;
  delete MessageNull_reflection_;
}

void protobuf_AddDesc_message_5fnull_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022message_null.proto\022\016hammer.message\"\r\n\013"
    "MessageNullB\022\n\016hammer.messageH\002", 71);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message_null.proto", &protobuf_RegisterTypes);
  MessageNull::default_instance_ = new MessageNull();
  MessageNull::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_message_5fnull_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fnull_2eproto {
  StaticDescriptorInitializer_message_5fnull_2eproto() {
    protobuf_AddDesc_message_5fnull_2eproto();
  }
} static_descriptor_initializer_message_5fnull_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

MessageNull::MessageNull()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MessageNull::InitAsDefaultInstance() {
}

MessageNull::MessageNull(const MessageNull& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MessageNull::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageNull::~MessageNull() {
  SharedDtor();
}

void MessageNull::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageNull::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageNull::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageNull_descriptor_;
}

const MessageNull& MessageNull::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_5fnull_2eproto();  return *default_instance_;
}

MessageNull* MessageNull::default_instance_ = NULL;

MessageNull* MessageNull::New() const {
  return new MessageNull;
}

void MessageNull::Swap(MessageNull* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MessageNull::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageNull_descriptor_;
  metadata.reflection = MessageNull_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

// @@protoc_insertion_point(global_scope)
