// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sc_auth_proof.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

namespace {

const ::google::protobuf::Descriptor* SCAuthProof_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SCAuthProof_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sc_5fauth_5fproof_2eproto() {
  protobuf_AddDesc_sc_5fauth_5fproof_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sc_auth_proof.proto");
  GOOGLE_CHECK(file != NULL);
  SCAuthProof_descriptor_ = file->message_type(0);
  static const int SCAuthProof_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCAuthProof, ret_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCAuthProof, player_id_),
  };
  SCAuthProof_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SCAuthProof_descriptor_,
      SCAuthProof::default_instance_,
      SCAuthProof_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCAuthProof, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCAuthProof, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SCAuthProof));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sc_5fauth_5fproof_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SCAuthProof_descriptor_, &SCAuthProof::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sc_5fauth_5fproof_2eproto() {
  delete SCAuthProof::default_instance_;
  delete SCAuthProof_reflection_;
}

void protobuf_AddDesc_sc_5fauth_5fproof_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023sc_auth_proof.proto\022\016hammer.message\"2\n"
    "\013SCAuthProof\022\020\n\010ret_code\030\001 \002(\005\022\021\n\tplayer"
    "_id\030\002 \001(\rB\022\n\016hammer.messageH\002", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sc_auth_proof.proto", &protobuf_RegisterTypes);
  SCAuthProof::default_instance_ = new SCAuthProof();
  SCAuthProof::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sc_5fauth_5fproof_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sc_5fauth_5fproof_2eproto {
  StaticDescriptorInitializer_sc_5fauth_5fproof_2eproto() {
    protobuf_AddDesc_sc_5fauth_5fproof_2eproto();
  }
} static_descriptor_initializer_sc_5fauth_5fproof_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SCAuthProof::kRetCodeFieldNumber;
const int SCAuthProof::kPlayerIdFieldNumber;
#endif  // !_MSC_VER

SCAuthProof::SCAuthProof()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SCAuthProof::InitAsDefaultInstance() {
}

SCAuthProof::SCAuthProof(const SCAuthProof& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SCAuthProof::SharedCtor() {
  _cached_size_ = 0;
  ret_code_ = 0;
  player_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SCAuthProof::~SCAuthProof() {
  SharedDtor();
}

void SCAuthProof::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SCAuthProof::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SCAuthProof::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SCAuthProof_descriptor_;
}

const SCAuthProof& SCAuthProof::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sc_5fauth_5fproof_2eproto();  return *default_instance_;
}

SCAuthProof* SCAuthProof::default_instance_ = NULL;

SCAuthProof* SCAuthProof::New() const {
  return new SCAuthProof;
}

void SCAuthProof::Swap(SCAuthProof* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata SCAuthProof::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SCAuthProof_descriptor_;
  metadata.reflection = SCAuthProof_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

// @@protoc_insertion_point(global_scope)
