// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sc_server_challeng_ack.proto

#ifndef PROTOBUF_sc_5fserver_5fchalleng_5fack_2eproto__INCLUDED
#define PROTOBUF_sc_5fserver_5fchalleng_5fack_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_sc_5fserver_5fchalleng_5fack_2eproto();
void protobuf_AssignDesc_sc_5fserver_5fchalleng_5fack_2eproto();
void protobuf_ShutdownFile_sc_5fserver_5fchalleng_5fack_2eproto();

class SCServerChallengeAck;

// ===================================================================

class SCServerChallengeAck : public ::google::protobuf::Message {
 public:
  SCServerChallengeAck();
  virtual ~SCServerChallengeAck();
  
  SCServerChallengeAck(const SCServerChallengeAck& from);
  
  inline SCServerChallengeAck& operator=(const SCServerChallengeAck& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCServerChallengeAck& default_instance();
  
  void Swap(SCServerChallengeAck* other);
  
  // implements Message ----------------------------------------------
  
  SCServerChallengeAck* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 ret_code = 1;
  inline bool has_ret_code() const;
  inline void clear_ret_code();
  static const int kRetCodeFieldNumber = 1;
  inline ::google::protobuf::int32 ret_code() const;
  inline void set_ret_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:hammer.message.SCServerChallengeAck)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 ret_code_;
  friend void  protobuf_AddDesc_sc_5fserver_5fchalleng_5fack_2eproto();
  friend void protobuf_AssignDesc_sc_5fserver_5fchalleng_5fack_2eproto();
  friend void protobuf_ShutdownFile_sc_5fserver_5fchalleng_5fack_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SCServerChallengeAck* default_instance_;
};
// ===================================================================


// ===================================================================

// SCServerChallengeAck

// required int32 ret_code = 1;
inline bool SCServerChallengeAck::has_ret_code() const {
  return _has_bit(0);
}
inline void SCServerChallengeAck::clear_ret_code() {
  ret_code_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 SCServerChallengeAck::ret_code() const {
  return ret_code_;
}
inline void SCServerChallengeAck::set_ret_code(::google::protobuf::int32 value) {
  _set_bit(0);
  ret_code_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace hammer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sc_5fserver_5fchalleng_5fack_2eproto__INCLUDED
