// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: luabind_pb_test.proto

#ifndef PROTOBUF_luabind_5fpb_5ftest_2eproto__INCLUDED
#define PROTOBUF_luabind_5fpb_5ftest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace hammer {
namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_luabind_5fpb_5ftest_2eproto();
void protobuf_AssignDesc_luabind_5fpb_5ftest_2eproto();
void protobuf_ShutdownFile_luabind_5fpb_5ftest_2eproto();


// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace hammer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_luabind_5fpb_5ftest_2eproto__INCLUDED
