// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "error_code.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"

void LuabindPB_ErrorCode_Register(lua_State* L) {
  luabind::module(L) [
    luabind::enum_("ErrorCode").def() [
      luabind::value("kErrorCode_Ok", 0),
      luabind::value("kErrorCode_ParseMessageError", 1),
      luabind::value("kErrorCode_InvalidError", 2),
      luabind::value("kErrorCode_AuthOk", 10),
      luabind::value("kErrorCode_NotPermission", 11),
      luabind::value("kErrorCode_BeenBanned", 12),
      luabind::value("kErrorCode_PasswordError", 13),
      luabind::value("kErrorCode_HasLogin", 14),
      luabind::value("kErrorCode_NonExistent", 15),
      luabind::value("kErrorCode_Existed", 16),
      luabind::value("kErrorCode_Timeout", 17)
    ]
  ];
}


//////////////////////////////////////////////////
void LuabindPB_error_code_RegisterAll(lua_State* L) {
  LuabindPB_ErrorCode_Register(L);
}

//////////////////////////////////////////////////
