// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "luabind_pb_test.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"


//////////////////////////////////////////////////
void LuabindPB_luabind_pb_test_RegisterAll(lua_State* L) {
}

//////////////////////////////////////////////////
